### ISSUE TITLE
why quakec?

### ISSUE THREAD

**Issue by nephatrine** [BraXi/pragma#1]
I understand the motivation to move away from architecture-dependent native binaries for mods, but QuakeC seems like a weird choice - particularly when you're looking to modernize a lot of the other subsystems from the look of it. Just seems odd to pick a scripting language unique to an even older game in your standalone base for new projects rather than an industry standard solution.

Something like WASM is enjoys wide support outside the Quake community so better compilers, runtimes, etc. all the time since there's a lot of people invested in that ecosystem and there's already been proof of concepts showing it working in Quake2. Does QuakeC perform better currently? Did you also compare other things like Q3's QVM solution? Would using a purely JIT or interpreted solution like Lua or AngelScript be a better, more flexible solution?

Maybe just a rationale section in the readme would help for this particular choice.

**Comment by BraXi** [comment]
pragma has started as an attempt to get vanilla engine compiling with modern tools and to replace native game code with QC. Over time I've restarted development as I felt the code was terrible and since then goals have stretched, more features were added, more crusty code dropped and so it goes :) I've personaly never considered diferent scripting languages, feeling that project fits a niche for Quake modders who are willing to use this to build/port their mods for a standalone releases that will not require Quake 1/2 installed, and for those that want to make idtech based games, but were thrown back by obscure formats like paletted images which are not as easy to work with.

I agree that original QC was a pain to work with, but FTE has greatly improved the language, currently pragma supports just a tiny number of language extensions and that may increase with time

QCVM is well separated, an experienced programmer may replace it without pain when desired ☺️

**Comment by nephatrine** [comment]
Interesting. Looks really neat. Wasn't aware of the history of the project so that makes a lot more sense.
